// Autogenerated with StateSmith
#include "gainOven.h"
// Some user .c file comment...
#include "smtest.h"
#include "stateFailure.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

static void ROOT_enter(gainOven* self);
static void ROOT_exit(gainOven* self);

static void COOKING_enter(gainOven* self);
static void COOKING_exit(gainOven* self);
static void COOKING_button_on_off_press(gainOven* self);
static void COOKING_do(gainOven* self);
static void COOKING_immediate_action(gainOven* self);
static void COOKING_inspection_on_command(gainOven* self);
static void COOKING_self_test_require(gainOven* self);

static void COOLDOWN_enter(gainOven* self);
static void COOLDOWN_exit(gainOven* self);
static void COOLDOWN_do(gainOven* self);
static void COOLDOWN_time_up(gainOven* self);

static void DOOROPEN_enter(gainOven* self);
static void DOOROPEN_exit(gainOven* self);
static void DOOROPEN_button_stop_pressed(gainOven* self);
static void DOOROPEN_do(gainOven* self);
static void DOOROPEN_door_close(gainOven* self);

static void HEATING_enter(gainOven* self);
static void HEATING_exit(gainOven* self);
static void HEATING_button_start_pause_press(gainOven* self);
static void HEATING_button_stop_pressed(gainOven* self);
static void HEATING_cooking_complete(gainOven* self);
static void HEATING_do(gainOven* self);
static void HEATING_door_open(gainOven* self);

static void PAUSE_enter(gainOven* self);
static void PAUSE_exit(gainOven* self);
static void PAUSE_button_start_pause_press(gainOven* self);
static void PAUSE_do(gainOven* self);

static void READY_enter(gainOven* self);
static void READY_exit(gainOven* self);
static void READY_do(gainOven* self);
static void READY_time_up(gainOven* self);

static void FAILURE_enter(gainOven* self);
static void FAILURE_exit(gainOven* self);
static void FAILURE_do(gainOven* self);
static void FAILURE_inspection_on_command(gainOven* self);
static void FAILURE_self_test_require(gainOven* self);

static void IMMEDIATE_enter(gainOven* self);
static void IMMEDIATE_exit(gainOven* self);
static void IMMEDIATE_button_on_off_press(gainOven* self);
static void IMMEDIATE_do(gainOven* self);

static void INSPECTION_enter(gainOven* self);
static void INSPECTION_exit(gainOven* self);
static void INSPECTION_do(gainOven* self);
static void INSPECTION_inspection_off_command(gainOven* self);

static void SELFTEST_enter(gainOven* self);
static void SELFTEST_exit(gainOven* self);
static void SELFTEST_do(gainOven* self);
static void SELFTEST_inspection_on_command(gainOven* self);
static void SELFTEST_self_test_fail(gainOven* self);
static void SELFTEST_self_test_pass(gainOven* self);

static void STANDBY_OFF_enter(gainOven* self);
static void STANDBY_OFF_exit(gainOven* self);
static void STANDBY_OFF_button_on_off_press(gainOven* self);
static void STANDBY_OFF_do(gainOven* self);
static void STANDBY_OFF_inspection_on_command(gainOven* self);

static void STANDBY_ON_enter(gainOven* self);
static void STANDBY_ON_exit(gainOven* self);
static void STANDBY_ON_button_on_off_press(gainOven* self);
static void STANDBY_ON_button_start_pause_press(gainOven* self);
static void STANDBY_ON_do(gainOven* self);
static void STANDBY_ON_inspection_on_command(gainOven* self);
static void STANDBY_ON_self_test_require(gainOven* self);

void gainOven_ctor(gainOven* self)
{
    memset(self, 0, sizeof(*self));
}

void gainOven_start(gainOven* self)
{
    ROOT_enter(self);
    // Transition to target state standby_off
    {
        // No need exit any states in this handler.
        
        // Enter towards target
        STANDBY_OFF_enter(self);
        
        // update state_id
        self->state_id = gainOven_StateId_STANDBY_OFF;
    } // end of transition code
}

void gainOven_dispatch_event(gainOven* self, enum gainOven_EventId event_id)
{
    gainOven_Func behavior_func = self->current_event_handlers[event_id];
    
    while (behavior_func != NULL)
    {
        self->ancestor_event_handler = NULL;
        behavior_func(self);
        behavior_func = self->ancestor_event_handler;
    }
}

const char* gainOven_state_id_to_string(const enum gainOven_StateId id)
{
    switch (id)
    {
        case gainOven_StateId_ROOT: return "ROOT";
        case gainOven_StateId_COOKING: return "COOKING";
        case gainOven_StateId_COOLDOWN: return "COOLDOWN";
        case gainOven_StateId_DOOROPEN: return "DOOROPEN";
        case gainOven_StateId_HEATING: return "HEATING";
        case gainOven_StateId_PAUSE: return "PAUSE";
        case gainOven_StateId_READY: return "READY";
        case gainOven_StateId_FAILURE: return "FAILURE";
        case gainOven_StateId_IMMEDIATE: return "IMMEDIATE";
        case gainOven_StateId_INSPECTION: return "INSPECTION";
        case gainOven_StateId_SELFTEST: return "SELFTEST";
        case gainOven_StateId_STANDBY_OFF: return "STANDBY_OFF";
        case gainOven_StateId_STANDBY_ON: return "STANDBY_ON";
        default: return "?";
    }
}

////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = ROOT_exit;
}

static void ROOT_exit(gainOven* self)
{
    // State machine root is a special case. It cannot be exited.
    (void)self;  // nothing to see here compiler. move along!
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state COOKING
////////////////////////////////////////////////////////////////////////////////

static void COOKING_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = COOKING_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = COOKING_button_on_off_press;
    self->current_event_handlers[gainOven_EventId_DO] = COOKING_do;
    self->current_event_handlers[gainOven_EventId_IMMEDIATE_ACTION] = COOKING_immediate_action;
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = COOKING_inspection_on_command;
    self->current_event_handlers[gainOven_EventId_SELF_TEST_REQUIRE] = COOKING_self_test_require;
    
    // state behavior:
    {
        // uml action: state_cooking();
        state_cooking();
    } // end of behavior code
}

static void COOKING_exit(gainOven* self)
{
    
    // state behavior:
    {
        // uml action: state_cooking();
        state_cooking();
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_IMMEDIATE_ACTION] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_SELF_TEST_REQUIRE] = NULL;  // no ancestor listens to this event
}

static void COOKING_button_on_off_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_ON_OFF_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_ON_OFF_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: standby_off
        // Transition to target state standby_off
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            STANDBY_OFF_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_STANDBY_OFF;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void COOKING_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: state_cooking();
        state_cooking();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}

static void COOKING_immediate_action(gainOven* self)
{
    // setup handler for next ancestor that listens to `IMMEDIATE_ACTION` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `IMMEDIATE_ACTION` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: immediate
        // Transition to target state immediate
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            IMMEDIATE_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_IMMEDIATE;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void COOKING_inspection_on_command(gainOven* self)
{
    // setup handler for next ancestor that listens to `INSPECTION_ON_COMMAND` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `INSPECTION_ON_COMMAND` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: inspection
        // Transition to target state inspection
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            INSPECTION_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_INSPECTION;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void COOKING_self_test_require(gainOven* self)
{
    // setup handler for next ancestor that listens to `SELF_TEST_REQUIRE` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `SELF_TEST_REQUIRE` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: selfTest
        // Transition to target state selfTest
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            SELFTEST_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_SELFTEST;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state COOLDOWN
////////////////////////////////////////////////////////////////////////////////

static void COOLDOWN_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = COOLDOWN_exit;
    self->current_event_handlers[gainOven_EventId_DO] = COOLDOWN_do;
    self->current_event_handlers[gainOven_EventId_TIME_UP] = COOLDOWN_time_up;
    
    // state behavior:
    {
    } // end of behavior code
}

static void COOLDOWN_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = COOKING_exit;
    self->current_event_handlers[gainOven_EventId_DO] = COOKING_do;  // the next ancestor that handles this event is COOKING
    self->current_event_handlers[gainOven_EventId_TIME_UP] = NULL;  // no ancestor listens to this event
}

static void COOLDOWN_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = COOKING_do;
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        
        // uml action: state_coolDown();
        state_coolDown();
        
        if (consume_event)
        {
            // Mark event as handled.
            self->ancestor_event_handler = NULL;
        }
    } // end of behavior code
}

static void COOLDOWN_time_up(gainOven* self)
{
    // setup handler for next ancestor that listens to `TIME_UP` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `TIME_UP` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: ready
        // Transition to target state ready
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            READY_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_READY;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state DOOROPEN
////////////////////////////////////////////////////////////////////////////////

static void DOOROPEN_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = DOOROPEN_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_STOP_PRESSED] = DOOROPEN_button_stop_pressed;
    self->current_event_handlers[gainOven_EventId_DO] = DOOROPEN_do;
    self->current_event_handlers[gainOven_EventId_DOOR_CLOSE] = DOOROPEN_door_close;
    
    // state behavior:
    {
    } // end of behavior code
}

static void DOOROPEN_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = COOKING_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_STOP_PRESSED] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = COOKING_do;  // the next ancestor that handles this event is COOKING
    self->current_event_handlers[gainOven_EventId_DOOR_CLOSE] = NULL;  // no ancestor listens to this event
}

static void DOOROPEN_button_stop_pressed(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_STOP_PRESSED` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_STOP_PRESSED` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: coolDown
        // Transition to target state coolDown
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            COOLDOWN_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_COOLDOWN;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void DOOROPEN_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = COOKING_do;
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        
        // uml action: state_doorOpen();
        state_doorOpen();
        
        if (consume_event)
        {
            // Mark event as handled.
            self->ancestor_event_handler = NULL;
        }
    } // end of behavior code
}

static void DOOROPEN_door_close(gainOven* self)
{
    // setup handler for next ancestor that listens to `DOOR_CLOSE` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `DOOR_CLOSE` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: heating
        // Transition to target state heating
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            HEATING_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_HEATING;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state HEATING
////////////////////////////////////////////////////////////////////////////////

static void HEATING_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = HEATING_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_START_PAUSE_PRESS] = HEATING_button_start_pause_press;
    self->current_event_handlers[gainOven_EventId_BUTTON_STOP_PRESSED] = HEATING_button_stop_pressed;
    self->current_event_handlers[gainOven_EventId_COOKING_COMPLETE] = HEATING_cooking_complete;
    self->current_event_handlers[gainOven_EventId_DO] = HEATING_do;
    self->current_event_handlers[gainOven_EventId_DOOR_OPEN] = HEATING_door_open;
    
    // state behavior:
    {
    } // end of behavior code
}

static void HEATING_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = COOKING_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_START_PAUSE_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_BUTTON_STOP_PRESSED] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_COOKING_COMPLETE] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = COOKING_do;  // the next ancestor that handles this event is COOKING
    self->current_event_handlers[gainOven_EventId_DOOR_OPEN] = NULL;  // no ancestor listens to this event
}

static void HEATING_button_start_pause_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_START_PAUSE_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_START_PAUSE_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: pause
        // Transition to target state pause
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            PAUSE_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_PAUSE;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void HEATING_button_stop_pressed(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_STOP_PRESSED` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_STOP_PRESSED` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: coolDown
        // Transition to target state coolDown
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            COOLDOWN_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_COOLDOWN;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void HEATING_cooking_complete(gainOven* self)
{
    // setup handler for next ancestor that listens to `COOKING_COMPLETE` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `COOKING_COMPLETE` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: coolDown
        // Transition to target state coolDown
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            COOLDOWN_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_COOLDOWN;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void HEATING_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = COOKING_do;
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        
        // uml action: state_heating();
        state_heating();
        
        if (consume_event)
        {
            // Mark event as handled.
            self->ancestor_event_handler = NULL;
        }
    } // end of behavior code
}

static void HEATING_door_open(gainOven* self)
{
    // setup handler for next ancestor that listens to `DOOR_OPEN` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `DOOR_OPEN` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: doorOpen
        // Transition to target state doorOpen
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            DOOROPEN_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_DOOROPEN;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state PAUSE
////////////////////////////////////////////////////////////////////////////////

static void PAUSE_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = PAUSE_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_START_PAUSE_PRESS] = PAUSE_button_start_pause_press;
    self->current_event_handlers[gainOven_EventId_DO] = PAUSE_do;
    
    // state behavior:
    {
    } // end of behavior code
}

static void PAUSE_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = COOKING_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_START_PAUSE_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = COOKING_do;  // the next ancestor that handles this event is COOKING
}

static void PAUSE_button_start_pause_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_START_PAUSE_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_START_PAUSE_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: heating
        // Transition to target state heating
        {
            // First, exit up to Least Common Ancestor COOKING.
            while (self->current_state_exit_handler != COOKING_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            HEATING_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_HEATING;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void PAUSE_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = COOKING_do;
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        
        // uml action: state_pause();
        //             // Check doorsensor to control speed and
        //             // set cooking message
        state_pause();
        // Check doorsensor to control speed and
        // set cooking message<EOF>
        
        if (consume_event)
        {
            // Mark event as handled.
            self->ancestor_event_handler = NULL;
        }
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state READY
////////////////////////////////////////////////////////////////////////////////

static void READY_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = READY_exit;
    self->current_event_handlers[gainOven_EventId_DO] = READY_do;
    self->current_event_handlers[gainOven_EventId_TIME_UP] = READY_time_up;
    
    // state behavior:
    {
    } // end of behavior code
}

static void READY_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = COOKING_exit;
    self->current_event_handlers[gainOven_EventId_DO] = COOKING_do;  // the next ancestor that handles this event is COOKING
    self->current_event_handlers[gainOven_EventId_TIME_UP] = NULL;  // no ancestor listens to this event
}

static void READY_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = COOKING_do;
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        
        // uml action: state_ready();
        state_ready();
        
        if (consume_event)
        {
            // Mark event as handled.
            self->ancestor_event_handler = NULL;
        }
    } // end of behavior code
}

static void READY_time_up(gainOven* self)
{
    // setup handler for next ancestor that listens to `TIME_UP` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `TIME_UP` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: standby_on
        // Transition to target state standby_on
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            STANDBY_ON_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_STANDBY_ON;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FAILURE
////////////////////////////////////////////////////////////////////////////////

static void FAILURE_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = FAILURE_exit;
    self->current_event_handlers[gainOven_EventId_DO] = FAILURE_do;
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = FAILURE_inspection_on_command;
    self->current_event_handlers[gainOven_EventId_SELF_TEST_REQUIRE] = FAILURE_self_test_require;
    
    // state behavior:
    {
        // uml action: stateFailureEntry();
        stateFailureEntry();
    } // end of behavior code
}

static void FAILURE_exit(gainOven* self)
{
    
    // state behavior:
    {
        // uml action: stateFailureExit();
        stateFailureExit();
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_SELF_TEST_REQUIRE] = NULL;  // no ancestor listens to this event
}

static void FAILURE_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: // state_failure();
        //             stateFailureDo();
        // state_failure();
        stateFailureDo();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}

static void FAILURE_inspection_on_command(gainOven* self)
{
    // setup handler for next ancestor that listens to `INSPECTION_ON_COMMAND` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `INSPECTION_ON_COMMAND` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: inspection
        // Transition to target state inspection
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            INSPECTION_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_INSPECTION;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void FAILURE_self_test_require(gainOven* self)
{
    // setup handler for next ancestor that listens to `SELF_TEST_REQUIRE` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `SELF_TEST_REQUIRE` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: selfTest
        // Transition to target state selfTest
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            SELFTEST_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_SELFTEST;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state IMMEDIATE
////////////////////////////////////////////////////////////////////////////////

static void IMMEDIATE_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = IMMEDIATE_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = IMMEDIATE_button_on_off_press;
    self->current_event_handlers[gainOven_EventId_DO] = IMMEDIATE_do;
    
    // state behavior:
    {
    } // end of behavior code
}

static void IMMEDIATE_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
}

static void IMMEDIATE_button_on_off_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_ON_OFF_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_ON_OFF_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: standby_off
        // Transition to target state standby_off
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            STANDBY_OFF_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_STANDBY_OFF;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void IMMEDIATE_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: state_immediate();
        state_immediate();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INSPECTION
////////////////////////////////////////////////////////////////////////////////

static void INSPECTION_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = INSPECTION_exit;
    self->current_event_handlers[gainOven_EventId_DO] = INSPECTION_do;
    self->current_event_handlers[gainOven_EventId_INSPECTION_OFF_COMMAND] = INSPECTION_inspection_off_command;
    
    // state behavior:
    {
    } // end of behavior code
}

static void INSPECTION_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_INSPECTION_OFF_COMMAND] = NULL;  // no ancestor listens to this event
}

static void INSPECTION_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: state_inspection();
        state_inspection();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}

static void INSPECTION_inspection_off_command(gainOven* self)
{
    // setup handler for next ancestor that listens to `INSPECTION_OFF_COMMAND` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `INSPECTION_OFF_COMMAND` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: standby_off
        // Transition to target state standby_off
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            STANDBY_OFF_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_STANDBY_OFF;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SELFTEST
////////////////////////////////////////////////////////////////////////////////

static void SELFTEST_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = SELFTEST_exit;
    self->current_event_handlers[gainOven_EventId_DO] = SELFTEST_do;
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = SELFTEST_inspection_on_command;
    self->current_event_handlers[gainOven_EventId_SELF_TEST_FAIL] = SELFTEST_self_test_fail;
    self->current_event_handlers[gainOven_EventId_SELF_TEST_PASS] = SELFTEST_self_test_pass;
    
    // state behavior:
    {
    } // end of behavior code
}

static void SELFTEST_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_SELF_TEST_FAIL] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_SELF_TEST_PASS] = NULL;  // no ancestor listens to this event
}

static void SELFTEST_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: state_selfTest();
        state_selfTest();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}

static void SELFTEST_inspection_on_command(gainOven* self)
{
    // setup handler for next ancestor that listens to `INSPECTION_ON_COMMAND` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `INSPECTION_ON_COMMAND` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: inspection
        // Transition to target state inspection
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            INSPECTION_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_INSPECTION;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void SELFTEST_self_test_fail(gainOven* self)
{
    // setup handler for next ancestor that listens to `SELF_TEST_FAIL` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `SELF_TEST_FAIL` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: failure
        // Transition to target state failure
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            FAILURE_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_FAILURE;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void SELFTEST_self_test_pass(gainOven* self)
{
    // setup handler for next ancestor that listens to `SELF_TEST_PASS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `SELF_TEST_PASS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: heating
        // Transition to target state heating
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            COOKING_enter(self);
            HEATING_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_HEATING;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STANDBY_OFF
////////////////////////////////////////////////////////////////////////////////

static void STANDBY_OFF_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STANDBY_OFF_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = STANDBY_OFF_button_on_off_press;
    self->current_event_handlers[gainOven_EventId_DO] = STANDBY_OFF_do;
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = STANDBY_OFF_inspection_on_command;
    
    // state behavior:
    {
    } // end of behavior code
}

static void STANDBY_OFF_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = NULL;  // no ancestor listens to this event
}

static void STANDBY_OFF_button_on_off_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_ON_OFF_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_ON_OFF_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: standby_on
        // Transition to target state standby_on
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            STANDBY_ON_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_STANDBY_ON;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void STANDBY_OFF_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: state_standby_off();
        state_standby_off();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}

static void STANDBY_OFF_inspection_on_command(gainOven* self)
{
    // setup handler for next ancestor that listens to `INSPECTION_ON_COMMAND` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `INSPECTION_ON_COMMAND` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: inspection
        // Transition to target state inspection
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            INSPECTION_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_INSPECTION;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STANDBY_ON
////////////////////////////////////////////////////////////////////////////////

static void STANDBY_ON_enter(gainOven* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STANDBY_ON_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = STANDBY_ON_button_on_off_press;
    self->current_event_handlers[gainOven_EventId_BUTTON_START_PAUSE_PRESS] = STANDBY_ON_button_start_pause_press;
    self->current_event_handlers[gainOven_EventId_DO] = STANDBY_ON_do;
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = STANDBY_ON_inspection_on_command;
    self->current_event_handlers[gainOven_EventId_SELF_TEST_REQUIRE] = STANDBY_ON_self_test_require;
    
    // state behavior:
    {
        // uml action: doorSensor = 1;
        self->vars.doorSensor = 1;
    } // end of behavior code
}

static void STANDBY_ON_exit(gainOven* self)
{
    
    // state behavior:
    {
    } // end of behavior code
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[gainOven_EventId_BUTTON_ON_OFF_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_BUTTON_START_PAUSE_PRESS] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_DO] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_INSPECTION_ON_COMMAND] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[gainOven_EventId_SELF_TEST_REQUIRE] = NULL;  // no ancestor listens to this event
}

static void STANDBY_ON_button_on_off_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_ON_OFF_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_ON_OFF_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: standby_off
        // Transition to target state standby_off
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            STANDBY_OFF_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_STANDBY_OFF;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void STANDBY_ON_button_start_pause_press(gainOven* self)
{
    // setup handler for next ancestor that listens to `BUTTON_START_PAUSE_PRESS` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `BUTTON_START_PAUSE_PRESS` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml guard: self->vars.doorSensor == 1
        // uml transition target: heating
        if (self->vars.doorSensor == 1)
        {
            // Transition to target state heating
            {
                // First, exit up to Least Common Ancestor ROOT.
                while (self->current_state_exit_handler != ROOT_exit)
                {
                    self->current_state_exit_handler(self);
                }
                
                // Enter towards target
                COOKING_enter(self);
                HEATING_enter(self);
                
                // update state_id
                self->state_id = gainOven_StateId_HEATING;
            } // end of transition code
            
            // Mark event as handled. Required because of transition.
            // self->ancestor_event_handler = NULL; // already done at top of function
            return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
        } // end of guard code
    } // end of behavior code
}

static void STANDBY_ON_do(gainOven* self)
{
    // setup handler for next ancestor that listens to `do` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `do` event
    
    // state behavior:
    {
        bool consume_event = false; // the `do` event is special in that it normally is not consumed.
        (void)consume_event; // avoid un-used variable compiler warning. StateSmith cannot (yet) detect if behavior action code sets `consume_event`.
        // note: no ancestor consumes this event, but we output `bool consume_event` anyway because a user's design might rely on it.
        
        // uml action: state_standby_on();
        state_standby_on();
        
        if (consume_event)
        {
            // Mark event as handled.
            // self->ancestor_event_handler = NULL; // already done at top of function
        }
    } // end of behavior code
}

static void STANDBY_ON_inspection_on_command(gainOven* self)
{
    // setup handler for next ancestor that listens to `INSPECTION_ON_COMMAND` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `INSPECTION_ON_COMMAND` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: inspection
        // Transition to target state inspection
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            INSPECTION_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_INSPECTION;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}

static void STANDBY_ON_self_test_require(gainOven* self)
{
    // setup handler for next ancestor that listens to `SELF_TEST_REQUIRE` event
    self->ancestor_event_handler = NULL; // no ancestor state handles `SELF_TEST_REQUIRE` event
    
    // state behavior:
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // uml transition target: selfTest
        // Transition to target state selfTest
        {
            // First, exit up to Least Common Ancestor ROOT.
            while (self->current_state_exit_handler != ROOT_exit)
            {
                self->current_state_exit_handler(self);
            }
            
            // Enter towards target
            SELFTEST_enter(self);
            
            // update state_id
            self->state_id = gainOven_StateId_SELFTEST;
        } // end of transition code
        
        // Mark event as handled. Required because of transition.
        // self->ancestor_event_handler = NULL; // already done at top of function
        return; // event processing immediately stops when a transition occurs. No other behaviors for this state are checked.
    } // end of behavior code
}


